{% set version = "0.4.0" %}

package:
  name: jupyterlab_robotmode
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/j/jupyterlab_robotmode/jupyterlab_robotmode-{{ version }}.tar.gz
  sha256: e6f337b87c4d4015a6edab9c902f8c412339ec479a9198d09d13a91b62370a61

build:
  noarch: python
  number: 1
  script: |-
    {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jupyterlab =3
    - jupyter-packaging
  run:
    - python >={{ python_min }}
    - jupyterlab >=3,<4

test:
  requires:
    - pip
    - m2-grep  # [win]
    - python {{ python_min }}
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - grep -iE "@marketsquare/jupyterlab_robotmode.*v{{ version }}.*OK" labextensions

about:
  home: https://github.com/MarketSquare/jupyterlab_robotmode
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE
    - jupyterlab_robotmode/labextension/static/third-party-licenses.json
  summary: 'A JupyterLab extension which adds a CodeMirror mode for Robot Framework syntax'
  dev_url: https://github.com/MarketSquare/jupyterlab_robotmode

extra:
  recipe-maintainers:
    - martinRenou
    - bollwyvl
